"""Recompute BIRD attrition and all-scheduled quality without provider calls.

The historical summary uses the intersection of four completed arms. This
separate, retrospective audit preserves that result and also counts every
scheduled question, treating a missing run as incorrect in that arm only.
"""

from __future__ import annotations

import hashlib
import json
from math import fsum
from pathlib import Path

from scipy.stats import binomtest

ROOT = Path(__file__).resolve().parents[2]
CONDITIONS = ("baseline", "baseline_repeat", "compiled", "manual_schema_prefetch")


def audit_cohort(root: Path, selection_root: Path | None = None) -> dict:
    source = selection_root or root
    pre = json.loads((source / "preflight.json").read_text())
    planned: set[tuple[str, int]] = set()
    rows: dict[str, dict] = {c: {} for c in CONDITIONS}
    failures: dict[str, set] = {c: set() for c in CONDITIONS}
    hashes = {}
    for db, split in sorted(pre["selections"].items()):
        compile_path = source / "schema_first" / db / "compile.json"
        if not compile_path.exists() or json.loads(compile_path.read_text())["status"] != "admitted":
            continue
        planned.update((db, int(q)) for q in split["test"])
        path = root / "schema_first" / db / "evaluation.json"
        payload = json.loads(path.read_text())
        hashes[str(path.relative_to(root))] = hashlib.sha256(path.read_bytes()).hexdigest()
        for run in payload["results"]:
            condition = run["condition"]
            key = (db, int(run["issue_number"]))
            if key not in planned or key in rows[condition]:
                raise ValueError(f"unexpected or duplicate result: {condition} {key}")
            rows[condition][key] = run
        for failure in payload["failures"]:
            failures[failure["condition"]].add((db, int(failure["question_id"])))
    if not planned:
        raise ValueError("no admitted families with scheduled questions")
    for condition in CONDITIONS:
        if (planned - rows[condition].keys()) - failures[condition]:
            raise ValueError(f"missing run without retained failure: {condition}")
    common = set.intersection(*(set(v) for v in rows.values()))
    correct = {c: {k for k, row in rows[c].items() if row["quality"]["overall"]} for c in CONDITIONS}
    base_only = len(correct["baseline"] - correct["compiled"])
    comp_only = len(correct["compiled"] - correct["baseline"])
    paired = set(rows["baseline"]) & set(rows["compiled"])
    reductions = {}
    for metric in ("requests", "total_tokens", "wall_latency_ms", "estimated_cost_usd"):
        # Built-in float sum changed in Python 3.12; keep retained audits stable.
        sums = {c: fsum(rows[c][k]["metrics"][metric] for k in sorted(paired))
                for c in ("baseline", "compiled")}
        reductions[metric] = 1 - sums["compiled"] / sums["baseline"]
    return {
        "scheduled_questions": len(planned), "four_arm_complete_questions": len(common),
        "quality_denominator": "all scheduled questions; missing runs count as incorrect in their own arm",
        "arms": {c: {"completed": len(rows[c]), "correct": len(correct[c]),
                     "missing": [list(k) for k in sorted(planned - rows[c].keys())]} for c in CONDITIONS},
        "baseline_only_correct": base_only, "compiled_only_correct": comp_only,
        "mcnemar_exact_p": float(binomtest(base_only, base_only + comp_only).pvalue) if base_only + comp_only else 1.0,
        "baseline_compiled_resource_pairs": len(paired), "paired_resource_reductions": reductions,
        "source_sha256": hashes,
    }


def build() -> dict:
    root = ROOT / "paper/results/bird"
    return {"schema": "bird-denominator-audit/v1", "analysis": "retrospective; no new executions",
            "provider_calls_executed": 0, "cohorts": {
                "primary": audit_cohort(root),
                "rotated": audit_cohort(root / "rotated_rerun", root),
                "second_model": audit_cohort(root / "replications/gpt-6-luna"),
                "train": audit_cohort(root / "train"),
            }}


def main() -> None:
    result = build()
    out = ROOT / "paper/results/bird/denominator_audit.json"
    out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    lines = [r"% generated by paper/scripts/audit_bird_denominators.py; do not edit",
             r"\begin{tabular}{@{}lrrrrrr@{}}", r"\toprule",
             r"Run & Scheduled & Complete & Base & Repeat & GAC & Manual \\", r"\midrule"]
    for key, label in (("primary", "Primary"), ("rotated", "Rotated"), ("second_model", "Second model"), ("train", "Train split")):
        row = result["cohorts"][key]
        cells = [label, str(row["scheduled_questions"]), str(row["four_arm_complete_questions"])]
        cells.extend(str(row["arms"][c]["correct"]) for c in CONDITIONS)
        lines.append(" & ".join(cells) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    (ROOT / "paper/iclr/tables/bird_denominators.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(ROOT)}; provider calls: 0")


if __name__ == "__main__":
    main()
