"""Provider-free reanalysis behind the ICLR 2027 revision (``improve-iclr.md`` Phase 2).

Every sub-command reads retained result files only, writes one JSON file under
``paper/results/iclr_revision/`` and, where the manuscript needs one, a LaTeX
tabular body under ``paper/iclr/tables/``.  No network or provider call is made.

Sub-commands: absolute, paired, multiplicity, order, manifest, catalog-audit,
overlap, frontier, clusters, mechanisms, all.
"""

from __future__ import annotations

import argparse
import ast
import json
import math
import statistics
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Callable, Sequence

import numpy as np
import pandas as pd
from scipy.stats import beta, binomtest, wilcoxon

ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "paper" / "results"
OUT = RESULTS / "iclr_revision"
TABLES = ROOT / "paper" / "iclr" / "tables"
GENERATED = "% generated by paper/scripts/iclr_revision_statistics.py {name}; do not edit\n"

ALPHA, DELTA, GRID_SIZE = 0.05, 0.10, 11
BOOTSTRAP_SEED, BOOTSTRAP_N = 20260802, 10_000

# --------------------------------------------------------------------------- families
FAMILIES: dict[str, dict[str, Any]] = {
    "issue_type": {
        "label": "Issue-type routing",
        "path": RESULTS / "github_natural_replication" / "results.json",
        "arms": {"baseline": "baseline", "compiled": "compiled", "manual": "macro"},
        "exact": "factuality_exact",
        "id": "issue_number",
        "group_prefix": "github-issue:",
    },
    "pr_outcome": {
        "label": "PR-outcome audit",
        "path": RESULTS / "github_workflow_families" / "pr_outcome" / "final" / "results.json",
        "arms": {"baseline": "baseline", "compiled": "compiled", "manual": "manual_pre_model"},
        "exact": "overall",
        "id": "issue_number",
        "group_prefix": "github-pr_outcome:",
    },
    "backlog_attention": {
        "label": "Backlog-attention routing",
        "path": RESULTS / "github_workflow_families" / "backlog_attention" / "final" / "results.json",
        "arms": {"baseline": "baseline", "compiled": "compiled", "manual": "manual_pre_model"},
        "exact": "overall",
        "id": "issue_number",
        "group_prefix": "github-backlog_attention:",
    },
}
CORE = RESULTS / "github_multirepo_pr_outcome_core" / "results.json"
BALANCED = RESULTS / "github_multirepo_pr_outcome_balanced" / "results.json"
FRONTIER = RESULTS / "github_multirepo_gate_frontier" / "results.json"
HF_PARQUET = RESULTS / "datasets" / "github_issues" / "train-00000-of-00001.parquet"
MULTIREPO_DATA = RESULTS / "datasets" / "github_multirepo"
METRICS = ("requests", "tool_calls", "total_tokens", "wall_latency_ms", "estimated_cost_usd")


# --------------------------------------------------------------------------- helpers
def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def dump(name: str, payload: dict[str, Any]) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{name}.json"
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return path


def write_table(name: str, subcommand: str, body: str) -> Path:
    TABLES.mkdir(parents=True, exist_ok=True)
    path = TABLES / f"{name}.tex"
    path.write_text(GENERATED.format(name=subcommand) + body.rstrip() + "\n")
    return path


def rows_for(family: str, arm: str) -> list[dict[str, Any]]:
    spec = FAMILIES[family]
    data = load(spec["path"])
    cond = spec["arms"][arm]
    rows = [r for r in data["results"] if r["condition"] == cond and int(r.get("repeat", 0)) == 0]
    return sorted(rows, key=lambda r: int(r[spec["id"]]))


def exact(family: str, row: dict[str, Any]) -> bool:
    return bool(row["quality"][FAMILIES[family]["exact"]])


def mean_median(values: Sequence[float]) -> tuple[float, float]:
    return float(statistics.mean(values)), float(statistics.median(values))


def bootstrap_ci(values: Sequence[float], stat: Callable = np.mean, *, seed: int = BOOTSTRAP_SEED) -> tuple[float, float]:
    """Same estimator as ``github_live_study.bootstrap_ci`` (percentile, 10,000 resamples)."""
    if not values:
        return float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    array = np.asarray(values, dtype=float)
    idx = rng.integers(0, len(array), size=(BOOTSTRAP_N, len(array)))
    samples = stat(array[idx], axis=1)
    lo, hi = np.quantile(samples, [0.025, 0.975])
    return float(lo), float(hi)


def bootstrap_ci_mean_legacy(values: Sequence[float]) -> tuple[float, float]:
    """Byte-identical reimplementation of ``github_live_study.bootstrap_ci`` (rng.choice)."""
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    array = np.asarray(values, dtype=float)
    samples = rng.choice(array, size=(BOOTSTRAP_N, len(array)), replace=True).mean(axis=1)
    lo, hi = np.quantile(samples, [0.025, 0.975])
    return float(lo), float(hi)


def wilcoxon_p(diffs: Sequence[float]) -> float:
    try:
        return float(wilcoxon(list(diffs), zero_method="zsplit", alternative="two-sided").pvalue)
    except ValueError:
        return 1.0


def cp_upper(k: int, n: int, conf: float) -> float:
    if n == 0 or k >= n:
        return 1.0
    if k == 0:
        return 1.0 - (1.0 - conf) ** (1.0 / n)
    return float(beta.ppf(conf, k + 1, n - k))


def one_sided_upper_95(k: int, n: int) -> float:
    return cp_upper(k, n, 0.95)


def gamma_for(m: int) -> float:
    return DELTA / (m * GRID_SIZE)


def n_min(m: int) -> int:
    n = 1
    while cp_upper(0, n, 1.0 - gamma_for(m)) > ALPHA:
        n += 1
    return n


def parse_grid_rows(notes: str) -> list[dict[str, Any]]:
    marker = "grid rows: "
    if marker not in notes:
        return []
    return ast.literal_eval(notes.split(marker, 1)[1].strip())


def fmt(x: float, nd: int = 1) -> str:
    return f"{x:,.{nd}f}"


def sci(x: float) -> str:
    return f"{x * 1e4:.2f}"  # USD x 1e-4


# --------------------------------------------------------------------------- T2.1 absolute
def cmd_absolute() -> dict[str, Any]:
    out: dict[str, Any] = {"families": {}, "pooled": {}}
    pooled: dict[str, dict[str, list[float]]] = {a: {m: [] for m in METRICS} for a in ("baseline", "compiled", "manual")}
    for fam, spec in FAMILIES.items():
        out["families"][fam] = {"label": spec["label"], "arms": {}}
        for arm in ("baseline", "compiled", "manual"):
            rows = rows_for(fam, arm)
            block: dict[str, Any] = {"n": len(rows), "exact": sum(exact(fam, r) for r in rows), "condition": spec["arms"][arm]}
            for m in METRICS:
                vals = [float(r["metrics"][m]) for r in rows]
                pooled[arm][m].extend(vals)
                mu, med = mean_median(vals)
                block[m] = {"mean": mu, "median": med, "sum": float(sum(vals))}
            out["families"][fam]["arms"][arm] = block
    for arm in pooled:
        out["pooled"][arm] = {m: {"mean": mean_median(v)[0], "median": mean_median(v)[1], "sum": float(sum(v)), "n": len(v)} for m, v in pooled[arm].items()}

    lines = [r"\begin{tabular}{@{}llrrrrr@{}}", r"\toprule",
             r"Family & Arm & Requests & Interfaces & Tokens & Latency (ms) & Cost (USD$\times10^{-4}$) \\",
             r"\midrule"]
    arm_label = {"baseline": "Baseline", "compiled": "Compiled", "manual": "Manual"}
    for fam, spec in FAMILIES.items():
        for i, arm in enumerate(("baseline", "compiled", "manual")):
            b = out["families"][fam]["arms"][arm]
            name = spec["label"] if i == 0 else ""
            lines.append(
                f"{name} & {arm_label[arm]} & {b['requests']['mean']:.2f} & {b['tool_calls']['mean']:.2f} & "
                f"{fmt(b['total_tokens']['mean'])} / {fmt(b['total_tokens']['median'],0)} & "
                f"{fmt(b['wall_latency_ms']['mean'],0)} / {fmt(b['wall_latency_ms']['median'],0)} & "
                f"{sci(b['estimated_cost_usd']['mean'])} / {sci(b['estimated_cost_usd']['median'])} \\\\"
            )
        lines.append(r"\addlinespace[2pt]")
    lines.append(r"\midrule")
    for i, arm in enumerate(("baseline", "compiled", "manual")):
        b = out["pooled"][arm]
        name = r"All ($n=90$)" if i == 0 else ""
        lines.append(
            f"{name} & {arm_label[arm]} & {b['requests']['mean']:.2f} & {b['tool_calls']['mean']:.2f} & "
            f"{fmt(b['total_tokens']['mean'])} / {fmt(b['total_tokens']['median'],0)} & "
            f"{fmt(b['wall_latency_ms']['mean'],0)} / {fmt(b['wall_latency_ms']['median'],0)} & "
            f"{sci(b['estimated_cost_usd']['mean'])} / {sci(b['estimated_cost_usd']['median'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_table("absolute_resources", "absolute", "\n".join(lines))
    dump("absolute_resources", out)
    return out


# --------------------------------------------------------------------------- T2.2 paired
def cmd_paired() -> dict[str, Any]:
    out: dict[str, Any] = {"families": {}, "discordance": {}}
    pooled_cells = Counter()
    for fam, spec in FAMILIES.items():
        base = {int(r[spec["id"]]): r for r in rows_for(fam, "baseline")}
        fam_out: dict[str, Any] = {}
        for arm in ("compiled", "manual"):
            cand = {int(r[spec["id"]]): r for r in rows_for(fam, arm)}
            common = sorted(set(base) & set(cand))
            contrast: dict[str, Any] = {"n_pairs": len(common)}
            for m in ("total_tokens", "wall_latency_ms", "estimated_cost_usd", "requests"):
                diffs = [float(cand[k]["metrics"][m]) - float(base[k]["metrics"][m]) for k in common]
                entry: dict[str, Any] = {
                    "mean_difference": float(statistics.mean(diffs)),
                    "mean_ci95": list(bootstrap_ci_mean_legacy(diffs)),
                    "wilcoxon_p": wilcoxon_p(diffs),
                    "aggregate_reduction": 1.0 - sum(float(cand[k]["metrics"][m]) for k in common) / sum(float(base[k]["metrics"][m]) for k in common),
                }
                if m == "wall_latency_ms":
                    entry["median_difference"] = float(statistics.median(diffs))
                    entry["median_ci95"] = list(bootstrap_ci(diffs, np.median, seed=BOOTSTRAP_SEED + 1))
                if m == "requests":
                    entry["difference_histogram"] = dict(Counter(int(d) for d in diffs))
                contrast[m] = entry
            fam_out[arm] = contrast
        # discordance (compiled vs baseline)
        cand = {int(r[spec["id"]]): r for r in rows_for(fam, "compiled")}
        common = sorted(set(base) & set(cand))
        b_only = sum(exact(fam, base[k]) and not exact(fam, cand[k]) for k in common)
        c_only = sum(exact(fam, cand[k]) and not exact(fam, base[k]) for k in common)
        both = sum(exact(fam, cand[k]) and exact(fam, base[k]) for k in common)
        neither = len(common) - b_only - c_only - both
        disc = b_only + c_only
        out["discordance"][fam] = {
            "n": len(common), "baseline_only": b_only, "compiled_only": c_only, "both": both, "neither": neither,
            "mcnemar_exact_p": float(binomtest(min(b_only, c_only), disc, 0.5).pvalue) if disc else 1.0,
            "compiled_only_failure_upper95": one_sided_upper_95(b_only, len(common)),
            "baseline_only_records": [k for k in common if exact(fam, base[k]) and not exact(fam, cand[k])],
            "compiled_only_records": [k for k in common if exact(fam, cand[k]) and not exact(fam, base[k])],
        }
        for key in ("n", "baseline_only", "compiled_only", "both", "neither"):
            pooled_cells[key] += out["discordance"][fam][key]
        out["families"][fam] = fam_out
    disc = pooled_cells["baseline_only"] + pooled_cells["compiled_only"]
    out["discordance"]["pooled"] = dict(pooled_cells) | {
        "mcnemar_exact_p": float(binomtest(min(pooled_cells["baseline_only"], pooled_cells["compiled_only"]), disc, 0.5).pvalue) if disc else 1.0,
        "compiled_only_failure_upper95": one_sided_upper_95(pooled_cells["baseline_only"], pooled_cells["n"]),
    }

    # paired table: compiled minus baseline
    def cell_ms(e: dict[str, Any], key: str, ci: str) -> str:
        return f"${e[key]:,.0f}$\\,ms $[{e[ci][0]:,.0f},\\,{e[ci][1]:,.0f}]$"

    lines = [r"\begin{tabular}{@{}llrr@{}}", r"\toprule", r"Family & Endpoint & Paired difference (95\% CI) & $p$ \\", r"\midrule"]
    for fam, spec in FAMILIES.items():
        c = out["families"][fam]["compiled"]
        tok, lat, cost = c["total_tokens"], c["wall_latency_ms"], c["estimated_cost_usd"]
        lines.append(rf"\multirow{{4}}{{*}}{{{spec['label'].split()[0]}}}")
        lines.append(_fix_sci(f" & Total tokens & ${tok['mean_difference']:,.1f}\\ [{tok['mean_ci95'][0]:,.1f},\\,{tok['mean_ci95'][1]:,.1f}]$ & ${tok['wilcoxon_p']:.1e}$ \\\\"))
        lines.append(_fix_sci(f" & Wall latency (mean) & {cell_ms(lat, 'mean_difference', 'mean_ci95')} & ${lat['wilcoxon_p']:.1e}$ \\\\"))
        lines.append(f" & Wall latency (median) & {cell_ms(lat, 'median_difference', 'median_ci95')} & --- \\\\")
        lines.append(_fix_sci(f" & Estimated cost & $-\\${abs(cost['mean_difference'])*1e4:.2f}\\times10^{{-4}}\\ [-{abs(cost['mean_ci95'][0])*1e4:.2f},\\,-{abs(cost['mean_ci95'][1])*1e4:.2f}]\\times10^{{-4}}$ & ${cost['wilcoxon_p']:.1e}$ \\\\"))
        lines.append(r"\addlinespace[1pt]")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_table("paired_statistics", "paired", "\n".join(lines))

    d = out["discordance"]
    lines = [r"\begin{tabular}{@{}lrrrrrr@{}}", r"\toprule",
             r"Family & $n$ & Both pass & Baseline-only & Compiled-only & McNemar $p$ & Upper bound \\", r"\midrule"]
    for fam, spec in FAMILIES.items():
        x = d[fam]
        lines.append(f"{spec['label'].split()[0]} & {x['n']} & {x['both']} & {x['baseline_only']} & {x['compiled_only']} & {x['mcnemar_exact_p']:.2f} & {100*x['compiled_only_failure_upper95']:.1f}\\% \\\\")
    x = d["pooled"]
    lines += [r"\midrule", f"Pooled & {x['n']} & {x['both']} & {x['baseline_only']} & {x['compiled_only']} & {x['mcnemar_exact_p']:.2f} & {100*x['compiled_only_failure_upper95']:.1f}\\% \\\\",
              r"\bottomrule", r"\end{tabular}"]
    write_table("discordance", "paired", "\n".join(lines))
    dump("paired_statistics", out)
    return out


def _fix_sci(line: str) -> str:
    """Render Python ``1.7e-06`` inside $...$ as ``1.7\times10^{-6}``."""
    import re
    return re.sub(r"(\d\.\d)e-0?(\d+)", lambda m: rf"{m.group(1)}\times10^{{-{int(m.group(2))}}}", line)


# --------------------------------------------------------------------------- T2.3 multiplicity
def cmd_multiplicity() -> dict[str, Any]:
    out: dict[str, Any] = {"alpha": ALPHA, "delta": DELTA, "grid_size": GRID_SIZE,
                           "n_min": {str(m): n_min(m) for m in (1, 2, 3, 4, 8, 16)},
                           "u_at_92": {str(m): cp_upper(0, 92, 1 - gamma_for(m)) for m in (1, 2)},
                           "artifacts": {}}
    # primary families
    for fam, spec in FAMILIES.items():
        data = load(spec["path"])
        art = data["compiler"]["artifact"]
        gate = art["gate"]
        rows = parse_grid_rows(gate["notes"])
        report = data["compiler"]["report"]
        if fam == "issue_type":
            cands = data["compiler"]["candidates"]
            reached = sum(1 for c in cands if c.get("gate") is not None)
            m = reached
            basis = "compiler.candidates: one candidate has gate == null (retired at synthesis)"
        else:
            m = 2 if "candidates mined        2" in report or "candidates mined 2" in report.replace("  ", " ") else int(report.split("candidates mined")[1].split()[0])
            basis = "compiler.report: candidates mined 2, dominated after calibration"
        n, k = gate["n_accepted"], gate["observed_violations"]
        out["artifacts"][fam] = {
            "label": spec["label"], "artifact_id": art["artifact_id"], "m": m, "m_basis": basis,
            "n": n, "k": k, "u_per_candidate": cp_upper(k, n, 1 - gamma_for(1)),
            "u_candidate_wide": cp_upper(k, n, 1 - gamma_for(m)),
            "grid_rows": rows, "retained_u": gate["risk_upper_bound"],
            "certificate_at_alpha": "compiler-wide" if cp_upper(k, n, 1 - gamma_for(m)) <= ALPHA else "per-candidate",
            "groups_for_compiler_wide": n_min(m),
        }
    # cross-repository (frozen search, m = 1)
    for name, path in (("core", CORE), ("balanced", BALANCED), ("gate_frontier", FRONTIER)):
        data = load(path)
        for repo, block in data["repositories"].items():
            comp = block.get("compiler") or (block.get("compilers") or {}).get("learned_gate")
            if not comp or not comp.get("artifact"):
                out["artifacts"][f"{name}:{repo}"] = {"status": block.get("status", "retired"), "m": 1}
                continue
            gate = comp["artifact"]["gate"]
            out["artifacts"][f"{name}:{repo}"] = {
                "m": 1, "m_basis": "freeze_one_candidate_before_calibration = true; one candidate mined",
                "frozen": comp["config"].get("freeze_one_candidate_before_calibration"),
                "n": gate["n_accepted"], "k": gate["observed_violations"], "retained_u": gate["risk_upper_bound"],
                "u_candidate_wide": cp_upper(gate["observed_violations"], gate["n_accepted"], 1 - gamma_for(1)),
                "grid_rows": parse_grid_rows(gate["notes"]),
            }
    lines = [r"\begin{tabularx}{\linewidth}{@{}lccc>{\raggedright\arraybackslash}Xc@{}}", r"\toprule",
             r"Family & $m$ & $n_\eta/k_\eta$ & $U_{\delta/|\Lambda|}$ / $U_{\delta/(m|\Lambda|)}$ & Certificate at $\alpha=0.05$ & Groups needed \\",
             r"\midrule"]
    for fam, spec in FAMILIES.items():
        a = out["artifacts"][fam]
        cert = "compiler-wide" if a["certificate_at_alpha"] == "compiler-wide" else r"per-candidate; compiler-wide at $\alpha\ge0.057$"
        lines.append(f"{spec['label']} & {a['m']} & {a['n']}/{a['k']} & {a['u_per_candidate']:.4f} / {a['u_candidate_wide']:.4f} & {cert} & {a['groups_for_compiler_wide']} \\\\")
    lines += [r"\addlinespace[2pt]", r"Cross-repository (7 admitted) & 1 & 92/0 & 0.0498 / 0.0498 & compiler-wide (frozen search) & 92 \\", r"\bottomrule", r"\end{tabularx}"]
    write_table("multiplicity_accounting", "multiplicity", "\n".join(lines))
    dump("multiplicity_accounting", out)
    return out


# --------------------------------------------------------------------------- T2.4 order
def cmd_order() -> dict[str, Any]:
    out: dict[str, Any] = {"families": {}}
    for fam, spec in FAMILIES.items():
        data = load(spec["path"])
        base = {int(r[spec["id"]]): r for r in rows_for(fam, "baseline")}
        comp = {int(r[spec["id"]]): r for r in rows_for(fam, "compiled")}
        if "schedule" in data:
            orders = {int(s["record_number"]): tuple(s["order"]) for s in data["schedule"]}
            design = "per-record permutation cycle; arms sequential (concurrency 1)"
        else:
            orders = {int(k): tuple(v) for k, v in data["condition_order"]["primary"]["assignments"].items()}
            design = data["condition_order"]["primary"]["method"] + "; blocked, concurrency 8"
        by_perm: dict[str, dict[str, Any]] = {}
        for perm in sorted(set(orders.values())):
            ids = [k for k, v in orders.items() if v == perm and k in base and k in comp]
            b = sum(float(base[k]["metrics"]["wall_latency_ms"]) for k in ids)
            c = sum(float(comp[k]["metrics"]["wall_latency_ms"]) for k in ids)
            by_perm["->".join(perm)] = {"n": len(ids), "wall_latency_reduction": 1 - c / b if b else None}
        pos_comp = Counter(v.index(spec["arms"]["compiled"]) for v in orders.values())
        by_position: dict[str, Any] = {}
        for pos in range(3):
            ids = [k for k, v in orders.items() if v.index(spec["arms"]["compiled"]) == pos and k in base and k in comp]
            b = sum(float(base[k]["metrics"]["wall_latency_ms"]) for k in ids)
            c = sum(float(comp[k]["metrics"]["wall_latency_ms"]) for k in ids)
            by_position[str(pos)] = {"n": len(ids), "wall_latency_reduction": 1 - c / b if b else None}
        ids = sorted(set(base) & set(comp))
        wall = 1 - sum(float(comp[k]["metrics"]["wall_latency_ms"]) for k in ids) / sum(float(base[k]["metrics"]["wall_latency_ms"]) for k in ids)
        prov = 1 - sum(float(comp[k]["metrics"]["provider_response_latency_ms"]) for k in ids) / sum(float(base[k]["metrics"]["provider_response_latency_ms"]) for k in ids)
        reductions = [v["wall_latency_reduction"] for v in by_perm.values() if v["wall_latency_reduction"] is not None]
        out["families"][fam] = {
            "design": design, "orders_histogram": {"->".join(k): v for k, v in Counter(orders.values()).items()},
            "compiled_position_histogram": dict(pos_comp), "by_permutation": by_perm, "by_compiled_position": by_position,
            "wall_latency_reduction": wall, "provider_latency_reduction": prov,
            "permutation_min": min(reductions), "permutation_max": max(reductions),
            "cached_input_tokens": {arm: sum(float(r["metrics"]["cached_input_tokens"]) for r in rows_for(fam, arm)) for arm in ("baseline", "compiled", "manual")},
        }
    allr = [v["permutation_min"] for v in out["families"].values()] + [v["permutation_max"] for v in out["families"].values()]
    out["overall_permutation_range"] = [min(allr), max(allr)]
    out["max_abs_wall_minus_provider_points"] = max(abs(v["wall_latency_reduction"] - v["provider_latency_reduction"]) * 100 for v in out["families"].values())
    dump("order_sensitivity", out)
    return out


# --------------------------------------------------------------------------- T2.5 manifest
def cmd_manifest() -> dict[str, Any]:
    runs = {fam: load(spec["path"])["run"] for fam, spec in FAMILIES.items()}
    core_run = load(CORE)["repositories"]["psf/requests"]["run"]
    gf_run = load(FRONTIER)["run"]
    rows: list[tuple[str, str, str]] = [
        ("Provider / model", f"OpenAI \\code{{{runs['pr_outcome']['model']}}} via the \\code{{openai-agents}} Responses interface", "run.model"),
        ("SDK versions", f"\\code{{openai-agents {runs['pr_outcome']['openai_agents_sdk']}}}, \\code{{openai {runs['pr_outcome']['openai_python']}}}, Python {runs['pr_outcome']['python']}, {runs['pr_outcome']['platform'].split('-arm64')[0]} arm64", "run.openai_agents_sdk, run.openai_python, run.python, run.platform"),
        ("Model settings", r"reasoning effort \code{low}, verbosity \code{low}, \code{parallel\_tool\_calls=False}, \code{store=False}", "paper/scripts/github_live_study.py:522-530"),
        ("Sampling", "temperature, top-p, and seed are not exposed for this model; the SDK sends none", "run.temperature (issue-type file)"),
        ("Turn and time limits", r"\code{max\_turns} 8 (families) / 6 (cross-repository); 120\,s per episode; no retries; failures kept in \code{failures[]}", "github_workflow_family_study.py run_batch; github_multirepo_pr_outcome_core.py:855-876"),
        ("Concurrency", "discovery 6 (PR, backlog) / 8 (issue-type, cross-repository); held-out arms one at a time per record (PR, backlog, cross-repository); blocked Latin design, 8-way (issue-type)", "run.resolved_config.concurrency; schedule[]; condition_order"),
        ("Condition order", "per-record permutation cycle over all six arm orders, five records per order", "schedule[].order"),
        ("Cache accounting", r"fields \code{input\_tokens}, \code{cached\_tokens}, \code{cache\_write\_tokens}, \code{output\_tokens}; no shared server state; cached tokens 0 in PR/backlog/cross-repository, non-zero in issue-type", "results[].metrics; paper/results/cache_accounting.json"),
        ("Pricing", r"USD per 1M tokens: input 0.20, cached 0.02, cache write 0.25, output 1.20 (list rates, 2026-08-02); cost $=$ (input $-$ cached $-$ write)$\cdot$0.20 $+$ cached$\cdot$0.02 $+$ write$\cdot$0.25 $+$ output$\cdot$1.20", "demos/live_runtime.py:58-65"),
        ("Data pins", r"\code{helmo/github-issues@e344be7b} parquet sha256 \code{09453eef\ldots} (tracked); four cross-repository parquets pinned by sha256 in \code{source\_manifest.json}", "paper/results/datasets/*"),
        ("Tool and effect pins", r"per-family \code{effect\_catalog\_version} digest, \code{tools\_hash}, \code{prompt\_hash}, \code{policy\_hash}, \code{entry\_contract\_version}", "compiler.artifact.guard.manifest_pins"),
        ("Run timestamps", f"one per study: {runs['issue_type']['timestamp_utc'][:10]}, {runs['pr_outcome']['timestamp_utc'][:10]}, {runs['backlog_attention']['timestamp_utc'][:10]} (families); {core_run['timestamp_utc'][:10]} (core); {gf_run['timestamp_utc'][:10]} (gate frontier); per-record timestamps not retained", "run.timestamp_utc"),
    ]
    lines = [r"\begin{tabularx}{\linewidth}{@{}l>{\raggedright\arraybackslash}X@{}}", r"\toprule", r"Key & Value \\", r"\midrule"]
    for key, value, _src in rows:
        lines.append(f"{key} & {value} \\\\")
    lines += [r"\bottomrule", r"\end{tabularx}"]
    write_table("live_provider_manifest", "manifest", "\n".join(lines))
    payload = {"rows": [{"key": k, "value": v, "source": s} for k, v, s in rows], "runs": runs, "core_run": core_run, "gate_frontier_run": gf_run}
    dump("live_provider_manifest", payload)
    return payload


# --------------------------------------------------------------------------- T2.6 catalog audit
def cmd_catalog_audit() -> dict[str, Any]:
    sys.path.insert(0, str(ROOT / "paper" / "scripts"))
    import github_live_study as live  # noqa: E402
    import github_multirepo_pr_outcome_core as core  # noqa: E402
    import github_workflow_family_study as fam_mod  # noqa: E402

    catalogs = {
        "issue_type": live.make_catalog(),
        "pr_outcome": fam_mod.make_catalog(fam_mod.FAMILIES["pr_outcome"]),
        "backlog_attention": fam_mod.make_catalog(fam_mod.FAMILIES["backlog_attention"]),
        "pr_outcome_core": core.make_catalog("psf/requests"),
    }
    declared: dict[str, Any] = {}
    for name, cat in catalogs.items():
        declared[name] = {"catalog_version": cat.catalog_version, "tools": {}}
        for tool, spec in cat.tools.items():
            declared[name]["tools"][tool] = {
                "effect": str(getattr(spec.effect, "value", spec.effect)),
                "capabilities": sorted(str(getattr(c, "value", c)) for c in spec.capabilities),
                "quota_attested": bool(spec.quota_attested),
            }
    # pinned digests in the artifacts
    pinned = {}
    for fam, spec in FAMILIES.items():
        pins = load(spec["path"])["compiler"]["artifact"]["guard"]["manifest_pins"]
        pinned[fam] = pins.get("effect_catalog_version")
    pinned["pr_outcome_core:psf/requests"] = load(CORE)["repositories"]["psf/requests"]["compiler"]["artifact"]["guard"]["manifest_pins"].get("effect_catalog_version")
    # empirical audit over every retained trace
    calls: Counter = Counter()
    contract = Counter()
    sources = [FAMILIES[f]["path"] for f in FAMILIES] + [
        RESULTS / "github_workflow_families" / "pr_outcome" / "headroom_ablation" / "results.json",
        RESULTS / "github_workflow_families" / "backlog_attention" / "headroom_ablation" / "results.json",
        RESULTS / "github_workflow_families" / "pr_outcome" / "pilot_v1" / "discovery_checkpoint.json",
        RESULTS / "github_workflow_families" / "backlog_attention" / "final" / "discovery_checkpoint.json",
        RESULTS / "github_natural_replication" / "discovery_checkpoint.json",
    ]
    for path in sources:
        if not path.exists():
            continue
        data = load(path)
        for row in data.get("results", []):
            for tool in row.get("tool_sequence", []):
                calls[tool] += 1
            q = row.get("quality") or {}
            if "tool_contract" in q and path.name == "results.json":
                contract["rows"] += 1
                contract["tool_contract_true"] += int(bool(q["tool_contract"]))
    for name, path in (("core", CORE), ("balanced", BALANCED), ("gate_frontier", FRONTIER)):
        for repo, block in load(path)["repositories"].items():
            for row in block.get("results", []) or []:
                for tool in row.get("tool_sequence", []):
                    calls[tool] += 1
                q = row.get("quality") or {}
                if "tool_contract" in q:
                    contract["rows"] += 1
                    contract["tool_contract_true"] += int(bool(q["tool_contract"]))
    declared_names = {t for c in declared.values() for t in c["tools"]}
    observed_raw = {t: n for t, n in calls.items() if not (t.startswith("compiled_") or t.startswith("manual_") or t.startswith("template_") or t == "issue_get_bundle")}
    undeclared = sorted(t for t in observed_raw if t not in declared_names)
    contract["note"] = "final result files only; discovery checkpoints carry the pre-regrade online grade"
    payload = {"declared": declared, "pinned_digests": pinned, "digest_match": {k: (pinned.get(k) == declared[k]["catalog_version"]) for k in ("issue_type", "pr_outcome", "backlog_attention")},
               "observed_calls": dict(calls), "raw_read_calls_by_tool": observed_raw, "undeclared_raw_tools": undeclared,
               "tool_contract": dict(contract), "note": "Tools are pure functions of the pinned parquet (execute_snapshot); no network or write path exists, so hidden-state and RNG checks are vacuous by construction."}
    lines = [r"\begin{tabular}{@{}llllr@{}}", r"\toprule", r"Family & Tool & Effect & Capabilities & Calls observed \\", r"\midrule"]
    labels = {"issue_type": "Issue-type", "pr_outcome": "PR-outcome", "backlog_attention": "Backlog", "pr_outcome_core": "Cross-repo"}
    for name, cat in declared.items():
        for i, (tool, spec) in enumerate(cat["tools"].items()):
            caps = ", ".join(c.replace("_", r"\_") for c in spec["capabilities"])
            lines.append(f"{labels[name] if i == 0 else ''} & \\code{{{tool.replace('_', chr(92)+'_')}}} & {spec['effect'].replace('_', chr(92)+'_')} & {caps} & {calls.get(tool, 0):,} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_table("live_catalog", "catalog-audit", "\n".join(lines))
    dump("live_catalog_audit", payload)
    return payload


# --------------------------------------------------------------------------- T2.7 overlap
def _ids(block: dict[str, Any], role: str) -> set[int]:
    key = "record_number" if "record_number" in (block["selection"][role][0] if block["selection"][role] else {}) else "issue_number"
    return {int(x[key]) for x in block["selection"][role]}


def _cal_ids(block: dict[str, Any]) -> set[int] | None:
    comp = block.get("compiler") or (block.get("compilers") or {}).get("learned_gate")
    if not comp or "splits" not in comp:
        return None
    return {int(g.rsplit(":", 1)[1]) for g in comp["splits"]["groups"]["calibration"]}


def cmd_overlap() -> dict[str, Any]:
    core, bal, gf = load(CORE)["repositories"], load(BALANCED)["repositories"], load(FRONTIER)["repositories"]
    out: dict[str, Any] = {"repositories": {}, "totals": Counter()}
    for repo in core:
        c, g, b = core[repo], gf.get(repo), bal.get(repo)
        entry: dict[str, Any] = {}
        if g:
            entry["core_vs_gate_frontier"] = {
                "discovery": len(_ids(c, "discovery") & _ids(g, "discovery")), "test": len(_ids(c, "test") & _ids(g, "test")),
                "core_test_n": len(_ids(c, "test")), "gf_test_n": len(_ids(g, "test")),
            }
            cc, gc = _cal_ids(c), _cal_ids(g)
            entry["core_vs_gate_frontier"]["calibration"] = len(cc & gc) if cc and gc else None
            entry["core_vs_gate_frontier"]["core_discovery_in_gf_test"] = len(_ids(c, "discovery") & _ids(g, "test"))
            for k in ("discovery", "test"):
                out["totals"][f"core_gf_{k}"] += entry["core_vs_gate_frontier"][k]
            if entry["core_vs_gate_frontier"]["calibration"] is not None:
                out["totals"]["core_gf_calibration"] += entry["core_vs_gate_frontier"]["calibration"]
        if b:
            entry["core_vs_balanced"] = {"discovery": len(_ids(c, "discovery") & _ids(b, "discovery")), "test": len(_ids(c, "test") & _ids(b, "test")), "core_discovery_in_balanced_test": len(_ids(c, "discovery") & _ids(b, "test"))}
            out["totals"]["core_bal_test"] += entry["core_vs_balanced"]["test"]
        if b and g:
            entry["balanced_vs_gate_frontier"] = {"discovery": len(_ids(b, "discovery") & _ids(g, "discovery")), "test": len(_ids(b, "test") & _ids(g, "test"))}
        entry["excluded_prior_record_numbers"] = {"core": c["selection"].get("excluded_prior_record_numbers"), "gate_frontier": g["selection"].get("excluded_prior_record_numbers") if g else None}
        out["repositories"][repo] = entry
    out["totals"] = dict(out["totals"])
    dump("cohort_overlap_audit", out)
    return out


# --------------------------------------------------------------------------- T2.8 frontier
def cmd_frontier() -> dict[str, Any]:
    gf = load(FRONTIER)
    core = load(CORE)
    bal = load(BALANCED)
    out: dict[str, Any] = {"gate_frontier": {"repositories": {}, "failures": gf["failures"]}, "core": {}, "balanced": {}}
    arms = ("baseline", "learned_gate", "support_only")
    pooled = {a: Counter() for a in arms}
    cost_sum = 0.0
    for repo, block in gf["repositories"].items():
        if block.get("status") == "failed_closed" or "results" not in block:
            out["gate_frontier"]["repositories"][repo] = {"status": block.get("status"), "sealed_test": len(block["selection"]["test"]), "error": (block.get("error") or "")[:300]}
            for row in (load(RESULTS / "github_multirepo_gate_frontier" / "repos" / "pytorch__pytorch" / "discovery_checkpoint.json")["results"] if repo == "pytorch/pytorch" else []):
                cost_sum += float(row["metrics"]["estimated_cost_usd"])
            continue
        entry: dict[str, Any] = {"sealed_test": len(block["selection"]["test"]), "arms": {}}
        for arm in arms:
            rows = [r for r in block["results"] if r["condition"] == arm]
            passes = sum(bool(r["quality"]["overall"]) for r in rows)
            disp = Counter(r["dispatch"].get("outcome") for r in rows if r.get("dispatch"))
            reasons = Counter(tuple(r["dispatch"].get("reasons") or ()) for r in rows if r.get("dispatch") and r["dispatch"].get("outcome") == "BASELINE")
            fallback_classes = Counter(next((t["class"] for t in block["selection"]["test"] if int(t["record_number"]) == int(r["record_number"])), "?") for r in rows if r.get("dispatch") and r["dispatch"].get("outcome") == "BASELINE")
            qs = sorted({round(float(r["dispatch"]["q"]), 4) for r in rows if r.get("dispatch") and "q" in r["dispatch"]})
            entry["arms"][arm] = {"completed": len(rows), "attempted": entry["sealed_test"], "exact": passes, "dispatch": dict(disp), "fallback_reasons": {"|".join(k): v for k, v in reasons.items()}, "fallback_classes": dict(fallback_classes), "q_values": qs,
                                  "requests_mean": statistics.mean(float(r["metrics"]["requests"]) for r in rows)}
            pooled[arm]["completed"] += len(rows); pooled[arm]["attempted"] += entry["sealed_test"]; pooled[arm]["exact"] += passes
            pooled[arm]["compacted"] += disp.get("COMPACTED", 0); pooled[arm]["fallback"] += disp.get("BASELINE", 0)
            cost_sum += sum(float(r["metrics"]["estimated_cost_usd"]) for r in rows)
        entry["coverage_curves"] = {k: block["coverage_curves"][k] for k in ("learned_gate", "support_only", "learned_gate_distinct_nonzero_coverage_levels")}
        lg = block["compilers"]["learned_gate"]["artifact"]["gate"]; so = block["compilers"]["support_only"]["artifact"]["gate"]
        entry["gates"] = {"learned": {"alpha": lg["alpha"], "grid_size": len(lg["grid"]), "threshold": lg["threshold"], "U": lg["risk_upper_bound"]}, "support_only": {"alpha": so["alpha"], "grid_size": len(so["grid"]), "threshold": so["threshold"], "U": so["risk_upper_bound"]}}
        entry["requests_reduction_learned"] = block["comparisons"]["baseline_vs_learned_gate"]["metrics"]["requests"]["aggregate_reduction"]
        cost_sum += sum(float(r["metrics"]["estimated_cost_usd"]) for r in load(RESULTS / "github_multirepo_gate_frontier" / "repos" / (repo.replace("/", "__")) / "discovery_checkpoint.json")["results"])
        out["gate_frontier"]["repositories"][repo] = entry
    out["gate_frontier"]["pooled"] = {a: dict(c) for a, c in pooled.items()}
    out["gate_frontier"]["retained_cost_usd_successful_attempts"] = round(cost_sum, 4)
    out["gate_frontier"]["comparisons"] = {k: {m: v["aggregate_reduction"] for m, v in gf["comparisons"][k]["metrics"].items() if m in ("requests", "total_tokens", "wall_latency_ms", "estimated_cost_usd")} for k in gf["comparisons"]}

    def dispatch_block(data: dict[str, Any]) -> dict[str, Any]:
        res: dict[str, Any] = {}
        for repo, block in data["repositories"].items():
            if "results" not in block:
                res[repo] = {"status": block.get("status")}
                continue
            rows = [r for r in block["results"] if r["condition"] == "compiled"]
            disp = Counter(r["dispatch"]["outcome"] for r in rows)
            reasons = Counter("|".join(r["dispatch"].get("reasons") or ()) for r in rows if r["dispatch"]["outcome"] == "BASELINE")
            gate = block["compiler"]["artifact"]["gate"]
            res[repo] = {"held_out": len(rows), "compacted": disp.get("COMPACTED", 0), "fallback": disp.get("BASELINE", 0), "fallback_reasons": dict(reasons),
                         "open_in_discovery": block["selection"].get("discovery_class_counts", {}).get("open"),
                         "requests_reduction": block["comparisons"]["baseline_vs_compiled"]["metrics"]["requests"]["aggregate_reduction"],
                         "grid_rows": parse_grid_rows(gate["notes"]), "admissible": gate["admissible"], "threshold": gate["threshold"]}
        return res
    out["core"] = dispatch_block(core)
    out["balanced"] = dispatch_block(bal)
    out["core"]["pooled"] = {"compacted": sum(v.get("compacted", 0) for v in out["core"].values() if isinstance(v, dict)), "held_out": sum(v.get("held_out", 0) for v in out["core"].values() if isinstance(v, dict))}
    out["balanced"]["pooled"] = {"compacted": sum(v.get("compacted", 0) for v in out["balanced"].values() if isinstance(v, dict)), "held_out": sum(v.get("held_out", 0) for v in out["balanced"].values() if isinstance(v, dict))}

    # Table 10 replacement
    lines = [r"\begin{tabularx}{\linewidth}{@{}lccc>{\raggedright\arraybackslash}Xr@{}}", r"\toprule",
             r"Repository & Held-out & Exact (B/L/S) & Dispatched & Coverage in sweep & Req.\ $\downarrow$ \\", r"\midrule"]
    for repo, e in out["gate_frontier"]["repositories"].items():
        if "arms" not in e:
            lines.append(f"\\code{{{repo}}} & 60 sealed & \\textsc{{retire}} & --- & none ($U=1$ at every $\\eta$) & --- \\\\")
            continue
        a = e["arms"]
        sup = f"{a['support_only']['exact']}" + ("$^\\dagger$" if a["support_only"]["completed"] < a["support_only"]["attempted"] else "")
        exact_cell = f"{a['baseline']['exact']}/{a['learned_gate']['exact']}/{sup}"
        levels = e["coverage_curves"]["learned_gate_distinct_nonzero_coverage_levels"]
        sweep = ", ".join((f"{lv:.4f} ($U={next(r['upper'] for r in e['coverage_curves']['learned_gate'] if abs(r['coverage']-lv)<1e-6):.3f}$, rejected)" if lv < 0.999 else "1.0") for lv in levels)
        lines.append(f"\\code{{{repo}}} & {e['sealed_test']} & {exact_cell} & {a['learned_gate']['dispatch'].get('COMPACTED',0)}/{e['sealed_test']} & {sweep} & {100*e['requests_reduction_learned']:.1f}\\% \\\\")
    lines += [r"\bottomrule", r"\end{tabularx}"]
    write_table("gate_frontier_disaggregated", "frontier", "\n".join(lines))

    lines = [r"\begin{tabular}{@{}llrrlr@{}}", r"\toprule", r"Protocol & Repository & Held-out & Dispatched & Fallback clause & Req.\ $\downarrow$ \\", r"\midrule"]
    for proto, block in (("Core", out["core"]), ("Balanced", out["balanced"])):
        for repo, e in block.items():
            if repo == "pooled":
                continue
            if "held_out" not in e:
                lines.append(f"{proto} & \\code{{{repo}}} & --- & \\textsc{{retire}} & --- & --- \\\\")
                continue
            clause = ", ".join(f"\\code{{{k.replace('_', chr(92)+'_')}}} ({v})" for k, v in e["fallback_reasons"].items()) or "---"
            lines.append(f"{proto} & \\code{{{repo}}} & {e['held_out']} & {e['compacted']}/{e['held_out']} & {clause} & {100*e['requests_reduction']:.1f}\\% \\\\")
        lines.append(r"\addlinespace[1pt]")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_table("multirepo_dispatch", "frontier", "\n".join(lines))
    dump("gate_frontier_reanalysis", out)
    return out


# --------------------------------------------------------------------------- T2.9 clusters
def _hf_frame() -> pd.DataFrame:
    frame = pd.read_parquet(HF_PARQUET, columns=["number", "created_at", "user", "updated_at", "id"])
    frame = frame.sort_values(["updated_at", "id"]).drop_duplicates("number", keep="last")
    frame["day"] = pd.to_datetime(frame["created_at"], utc=True).dt.strftime("%Y-%m-%d")
    frame["month"] = frame["day"].str[:7]
    frame["author"] = frame["user"].apply(lambda u: (u or {}).get("login") if isinstance(u, dict) else str(u))
    return frame.set_index("number")


def _cluster_stats(frame: pd.DataFrame, ids: Sequence[int]) -> dict[str, Any]:
    sub = frame.loc[[i for i in ids if i in frame.index]]
    stats = {"n": len(ids), "matched": len(sub), "distinct_days": int(sub["day"].nunique()), "distinct_months": int(sub["month"].nunique()), "distinct_authors": int(sub["author"].nunique()),
             "day_span_days": int((pd.to_datetime(sub["day"]).max() - pd.to_datetime(sub["day"]).min()).days) if len(sub) else None}
    for key in ("distinct_days", "distinct_months", "distinct_authors"):
        stats[f"U_at_{key}"] = cp_upper(0, stats[key], 1 - gamma_for(1))
    return stats


def cmd_clusters() -> dict[str, Any]:
    out: dict[str, Any] = {"cohorts": {}}
    hf = _hf_frame()
    for fam, spec in FAMILIES.items():
        cal = [int(g.rsplit(":", 1)[1]) for g in load(spec["path"])["compiler"]["splits"]["groups"]["calibration"]]
        out["cohorts"][fam] = {"label": spec["label"], "source": "huggingface/datasets"} | _cluster_stats(hf, cal)
    core = load(CORE)["repositories"]
    for repo, block in core.items():
        if "compiler" not in block:
            continue
        slug = repo.replace("/", "__")
        if repo == "huggingface/datasets":
            frame = hf
        else:
            p = MULTIREPO_DATA / slug / "snapshot.parquet"
            if not p.exists():
                out["cohorts"][f"core:{repo}"] = {"status": "parquet not available locally"}
                continue
            frame = pd.read_parquet(p, columns=["number", "created_at", "user"])
            frame = frame.drop_duplicates("number", keep="last")
            frame["day"] = pd.to_datetime(frame["created_at"], utc=True).dt.strftime("%Y-%m-%d")
            frame["month"] = frame["day"].str[:7]
            frame["author"] = frame["user"].apply(lambda u: (u or {}).get("login") if isinstance(u, dict) else str(u))
            frame = frame.set_index("number")
        cal = [int(g.rsplit(":", 1)[1]) for g in block["compiler"]["splits"]["groups"]["calibration"]]
        out["cohorts"][f"core:{repo}"] = {"label": repo, "source": repo} | _cluster_stats(frame, cal)
    prim = [out["cohorts"][f] for f in FAMILIES]
    out["primary_ranges"] = {"distinct_days": [min(c["distinct_days"] for c in prim), max(c["distinct_days"] for c in prim)],
                             "distinct_authors": [min(c["distinct_authors"] for c in prim), max(c["distinct_authors"] for c in prim)],
                             "distinct_months": [min(c["distinct_months"] for c in prim), max(c["distinct_months"] for c in prim)]}
    lines = [r"\begin{tabular}{@{}lrrrrrr@{}}", r"\toprule", r"Cohort & $n$ & Days & Months & Authors & $U$ at days & $U$ at authors \\", r"\midrule"]
    for key, c in out["cohorts"].items():
        if "distinct_days" not in c:
            continue
        label = c["label"] if not key.startswith("core:") else f"Core: \\code{{{c['label']}}}"
        lines.append(f"{label} & {c['n']} & {c['distinct_days']} & {c['distinct_months']} & {c['distinct_authors']} & {c['U_at_distinct_days']:.3f} & {c['U_at_distinct_authors']:.3f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_table("effective_units", "clusters", "\n".join(lines))
    dump("effective_units", out)
    return out


# --------------------------------------------------------------------------- T2.10 mechanisms
MECHANISMS: list[dict[str, str]] = [
    {"hazard": r"Ungrounded argument \code{issue\_get\_comments.limit=100}, recurring in 132/132 discovery traces", "observed": "issue-type, held-out \\#4420 family", "guard": "provenance + synthesis (stage 1/4): \\code{ungroundable\\_slot}", "replay": "replays the literal; emits the three-read program", "source": "github\\_natural\\_replication/results.json \\code{compiler.candidates[0]}"},
    {"hazard": "Clean tool replay, wrong downstream answer (Markdown URL dropped, issue 6602)", "observed": "natural-order study, 17/18 $\\to$ 18/18 after checked rendering", "guard": "continuation contract (post-model)", "replay": "accepts the answer", "source": "github\\_natural\\_live/continuation\\_replay.json"},
    {"hazard": "Getter-named method that mutates state on 36/36 calls", "observed": "BFCL executed gold plans", "guard": "signed effect declaration (stage 2)", "replay": "compiles a write into the region", "source": "external\\_benchmarks/bfcl\\_compiler\\_execution.json"},
    {"hazard": "API-documentation prologue before the hot prefix", "observed": "AppWorld released runs, 4,679/4,680 ReAct and plan-and-execute", "guard": "position invariant, Eq.~(2), at dispatch", "replay": "dispatches out of position", "source": "external\\_benchmarks/appworld\\_dispatch\\_preflight.json"},
    {"hazard": "Suffix region dispatched at entry: reordered and duplicated calls", "observed": "archived pilot, 16.7\\% pass", "guard": "position invariant (compile-time \\code{prefix\\_only})", "replay": "ships the fault", "source": "github\\_live/pilot\\_2026-08-03/"},
    {"hazard": "Result outside the induced hull (\\code{pr.state=open}; 40/120 core records)", "observed": "cross-repository core protocol", "guard": "induced verifier $V$; clean fallback", "replay": "answers from an unseen class unchecked", "source": "github\\_multirepo\\_pr\\_outcome\\_core/results.json \\code{dispatch.reasons}"},
    {"hazard": "Projection type mismatch (\\code{merged\\_at}, record 7199; 13 events)", "observed": "PR-outcome pilot", "guard": "composite projection verifier; fallback", "replay": "emits a malformed evidence object", "source": "pr\\_outcome/pilot\\_v1/failed\\_attempt\\_projection\\_2026-08-05.json"},
    {"hazard": "Recurrent but under-supported families ($n_{\\max}$ 26, 8, 15 $<$ 92)", "observed": "NESTFUL, API-Bank, BFCL", "guard": "stage-6 exact gate", "replay": "deploys on recurrence alone", "source": "nestful/results.json; api\\_bank\\_execution.json; bfcl\\_compiler\\_execution.json"},
    {"hazard": "Skewed calibration pool (84/30/2 classes)", "observed": "\\code{pytorch/pytorch}, core protocol", "guard": "stage-6 exact gate ($U=1.0$)", "replay": "deploys", "source": "github\\_multirepo\\_pr\\_outcome\\_core/results.json \\code{repository\\_failures[0]}"},
]


def cmd_mechanisms() -> dict[str, Any]:
    lines = [r"\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}p{0.29\linewidth}>{\raggedright\arraybackslash}p{0.18\linewidth}>{\raggedright\arraybackslash}p{0.17\linewidth}>{\raggedright\arraybackslash}X@{}}",
             r"\toprule", r"Hazard (where observed) & Guard that caught it & Recurrence-only replay & Retained source (\code{paper/results/}) \\", r"\midrule"]
    for m in MECHANISMS:
        source = m["source"].replace("\\_", "_")
        lines.append(f"{m['hazard']} ({m['observed']}) & {m['guard']} & {m['replay']} & {{\\scriptsize\\path{{{source}}}}} \\\\")
        lines.append(r"\addlinespace[1pt]")
    lines += [r"\bottomrule", r"\end{tabularx}"]
    write_table("mechanism_removal", "mechanisms", "\n".join(lines))
    payload = {"rows": MECHANISMS}
    dump("mechanism_removal", payload)
    return payload


# --------------------------------------------------------------------------- main
COMMANDS: dict[str, Callable[[], dict[str, Any]]] = {
    "absolute": cmd_absolute, "paired": cmd_paired, "multiplicity": cmd_multiplicity, "order": cmd_order,
    "manifest": cmd_manifest, "catalog-audit": cmd_catalog_audit, "overlap": cmd_overlap, "frontier": cmd_frontier,
    "clusters": cmd_clusters, "mechanisms": cmd_mechanisms,
}


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=[*COMMANDS, "all"])
    args = parser.parse_args(argv)
    names = list(COMMANDS) if args.command == "all" else [args.command]
    for name in names:
        COMMANDS[name]()
        print(f"[ok] {name}")


if __name__ == "__main__":
    main()
